version: 1.0
component: deployment
runAs: root
env:
  variables:
    key1: "value1"
    key2: "value2"

files:
  # This section is to define how the files in the artifact shall
# be put on the compute instance
- source: /
  destination: /tmp/integrationTestFolder
