version: 1.0
component: deployment
runAs: root
env:
  variables:
    key1: "value1"
    key2: "value2"

files:
  # This section is to define how the files in the artifact shall
# be put on the compute instance
- source: /
  destination: /tmp/integrationTestFolder

steps:
  # This section is to define the scripts that each step shall run on the instance after file copy.
  - stepType: Command
    name: TestRunSingleCommand
    command: echo ${version}
    runAs: root
    timeoutInSeconds: 300
