version: 1.0 
component: deployment 
runAs: root
env: 
    variables:        
timeoutInSeconds:  
files:  
  - source: /
    destination: /home/opc/tmp/integrationTestFolder                              
steps:                              
  - stepType: Command 
    name: TestRunSingleCommand
    command: ls
    runAs: root
    timeoutInSeconds: 300
 
