version: 0.1
component: build
timeoutInSeconds: 900
failImmediatelyOnError: true
runAs: root
shell: bash

pipeline {
  agent any
  stages {
    stage('checkout') {
      steps {
        echo 'Hello World'
        sh 'echo `pwd`'
        sh 'ls -alrt'
      }
    }
    stage('build') {
      steps {
        sh 'tar -czf artifacts.tar.gz ./*.sh'
      }
    }
    stage("OCI Upload Artifact") {
        steps {
          uploadArtifactDetailsList: [[artifactPath: 'artifacts.tar.gz',
          repositoryType: 'GENERIC',
          sourcePath: 'artifacts.tar.gz',
          version: "1.$BUILD_NUMBER"],
          [artifactPath: 'deployment_spec.yaml',
          repositoryType: 'GENERIC',
          sourcePath: 'deployment_spec.yaml',
          version: "1.$BUILD_NUMBER"]
          ])
        }
    }
    stage('Trigger Deployment') {
        steps {
          OCIDeployment(argumentVal: JsonOutput.toJson(args_map),
          displayName: "BuildtoDeploy${BUILD_NUMBER}",
          pollingConfig: [timeoutSeconds: 600, "pollingIntervalSeconds" : 5], executionMode: 'SYNC'
          )
      }
    }  
  }
}
